#!/bin/env python3

import click
from pathlib import Path
import cibmodules.update_cib_settings as cib

@click.command()
@click.option('--session', '-s', type=str, default=None,
              help='Session to be used to enable/disable the system. If None it will take the first session in the file')
@click.argument('oks_session_file', type=click.Path(exists=True, dir_okay=False, writable=True))
@click.argument('jsonfile', type=click.Path(exists=True, dir_okay=False))
def cli(oks_session_file, jsonfile, session) -> None :
    """ 
    Script to take a cib json file like one present in this source tree
    and sets the oks representation accordingly
    """
    cib.update_cib_settings(oks_session_file, jsonfile, session)
    
    
if __name__ == '__main__':
  cli()
